import 'package:flutter/widgets.dart';
import 'package:get/get.dart';

class LanguageConfig extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'Welcome!': 'Welcome...!',
          'Logout': 'Logout',
          'Sign In': 'Sign In',
          'Email Address': 'Email Address',
          'Enter Your Email Address': 'Enter Your Email Address',
          'Password': 'Password',
          'Enter Your Password': 'Email Address',
          'Sign Up as User': 'Sign Up as User',
          'Sign Up as a Shop': 'Sign Up as a Shop',
          'No Account. Click below buttons to SignUp':
              'No Account. Click below buttons to SignUp',
          'All Shop Promos': 'All Shop Promos',
          'Saved Promos': 'Saved Promos',
          'Shop Dashboard': 'Shop Dashboard',
          'Search': 'Search',
          'Update': 'Update',
          'Food Name': 'Food Name',
          'Price': 'Price',
          'Pinned': 'Pinned',
          'Pin Shop': 'Pin Shop',
          'Back': 'Back',
          'Shops': 'Shops',
          'Foods': 'Foods',
          'Shop Name': 'Shop Name',
          'Add': 'Add',
          'Added Successfully': 'Added Successfully',
          'Error Occured': 'Error Occured',
          'Select An Image': 'Select An Image',
          'Please select an image': 'Please select an image',
          'Enter Food Name': 'Enter Food Name',
          'Enter the Price': 'Enter the Price',
          'View Saved Promos': 'View Saved Promos',
          'View All Promos': 'View All Promos',
          'Add Promo': 'Add Promo',
          'Promo Description': 'Promo Description',
          'Last Date': 'Last Date',
          'Date': 'Date',
          'Settings': 'Settings',
          'Change Language': 'Change Language',
          'Please choose a language': 'Please choose a language',
          'Go': 'Go',
          'Sign Up Shop': 'Sign Up Shop',
          'By Signing up I understand and agree to Terms and Conditions':
              'By Signing up I understand and agree to Terms and Conditions',
          'Sign Up': 'Sign Up',
          'Already have an Account. Click here to Sign In':
              'Already have an Account. Click here to Sign In',
          'Enter Your Shop Name': 'Enter Your Shop Name',
          'Country': 'Country/Location',
          'Enter Your Country': 'Enter Your Country',
          'Username': 'Username',
          'Enter Your Username': 'Enter Your Username',
          'Dashboard': 'Dashboard',
          'Edit Details': 'Edit Details',
          'Promos': 'Promos',
          'Food Hunt': 'Food Hunt',
          'Name': 'Name',
          'Country/Location': 'Country/Location',
          'Updated Successfully': 'Updated Successfully',
          'View Shops': 'View Shops',
          'Sign Up User': 'Sign Up User',
          'Check Username and Password': 'Check Username and Password',
          'Change Theme': 'Change Theme',
          'Please choose a Theme': 'Please choose a Theme',
        },
        'si_LK': {
          'Welcome!': 'ආයුබෝවන්...!',
          'Logout': 'ඉවත්වන්න',
          'Sign In': 'පිවිසෙන්න',
          'Email Address': 'E තැපැල් ලිපිනය',
          'Enter Your Email Address': 'තැපැල් ලිපිනය ඇතුලත් කරන්න',
          'Password': 'මුරපදය',
          'Enter Your Password': 'මුරපදය ඇතුලත් කරන්න',
          'Sign Up as User': 'පරිශීලකයෙකු ලෙස',
          'Sign Up as a Shop': ' ආයතනයක් ලෙස',
          'No Account. Click below buttons to SignUp': 'පහතින් ලියාපදිංචිවන්න',
          'All Shop Promos': 'සියලු දැන්වීම්',
          'Saved Promos': 'සුරැකි දැන්වීම්',
          'Shop Dashboard': 'මුල් පිටුව',
          'Search': 'සොයන්න',
          'Update': 'අලුත් කරන්න',
          'Food Name': 'ආහාරයේ නම',
          'Price': 'මිල',
          'Pinned': 'සාර්තකයි',
          'Pin Shop': 'පින් කරන්න',
          'Shops': 'කඩ',
          'Back': 'පසුපසට යන්න',
          'Foods': 'ආහාර',
          'Shop Name': 'ආයතනයේ නම',
          'Add': 'ඇතුලත් කරන්න',
          'Added Successfully': 'සාර්තකව ඇතුලත් කරන ලදී',
          'Error Occured': 'ගැටලුවකි',
          'Select An Image': 'රූපයක් තෝරන්න',
          'Please select an image': 'රූපයක් තෝරන්න',
          'Enter Food Name': 'ආහාරයේ නම ඇතුලත් කරන්න',
          'Enter the Price': 'මිල ඇතුලත් කරන්න',
          'View Saved Promos': 'සුරැකි දැන්වීම්',
          'View All Promos': 'සියලු දැන්වීම්',
          'Add Promo': 'දැන්වීම් ඇතුලත් කරන්න',
          'Promo Description': 'දැන්වීම් විස්තර',
          'Last Date': 'අවසන් දිනය',
          'Date': 'දිනය',
          'Settings': 'වෙනස් කිරීම්',
          'Change Language': 'භාශාව',
          'Please choose a language': 'භාශාවක් තෝරන්න',
          'Go': 'ඉවත්වන්න',
          'Sign Up Shop': 'ආයතනයක්',
          'By Signing up I understand and agree to Terms and Conditions':
              'සියලු නීතිවලට එකඟ වෙමි',
          'Sign Up': 'ලියාපදිංචිවන්න',
          'Already have an Account. Click here to Sign In':
              'ලියාපදිංචි වී ඇත්නම් ඇතුලුවන්න',
          'Enter Your Shop Name': 'ආයතනයේ නම ඇතුලත් කරන්න',
          'Country': 'ස්ථානය ',
          'Enter Your Country': 'ස්ථානය ඇතුලත් කරන්න',
          'Username': 'නම',
          'Enter Your Username': 'නම ඇතුලත් කරන්න',
          'Dashboard': 'මුල් පිටුව',
          'Edit Details': 'වෙනස්කම්',
          'Promos': 'දැන්වීම්',
          'Food Hunt': 'සුරැකි-දෑ',
          'Name': 'නම',
          'Country/Location': 'ස්ථානය',
          'Updated Successfully': 'සාර්තකව අලුත් කරන ලදී',
          'View Shops': 'ආයතන පෙන්වන්න',
          'Sign Up User': 'පරිශීලක',
          'Check Username and Password': 'නම හෝ මුරපදය වැරදියි',
          'Change Theme': 'පාට මාරුකරන්න',
          'Please choose a Theme': 'පාටක් තෝරන්න',
        },
      };
}
